# Generated by Django 4.0.4 on 2022-05-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kursach', '0002_product_price_product_supplier_supplier_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='city',
            new_name='details',
        ),
    ]
