# Generated by Django 4.0.4 on 2022-05-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kursach', '0003_rename_city_supplier_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='details',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
