# Generated by Django 4.0.4 on 2022-05-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kursach', '0005_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
