# Generated by Django 4.0.4 on 2022-05-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kursach', '0006_alter_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier2',
            field=models.CharField(choices=[], default=0, max_length=50),
        ),
    ]
