# Generated by Django 4.0.4 on 2022-05-15 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kursach', '0007_remove_product_supplier_product_supplier2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier2',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Kursach.supplier'),
        ),
    ]
