# Generated by Django 4.0.4 on 2022-05-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kursach', '0008_remove_product_supplier2_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargrade', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier'},
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='details',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
