# Generated by Django 4.0.4 on 2022-05-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kursach', '0009_grades_alter_supplier_options_alter_product_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='chargrade',
            field=models.CharField(max_length=1000),
        ),
    ]
